# Generated by Django 3.0.8 on 2020-08-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidSA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popdensitydata',
            name='tilenumber',
            field=models.IntegerField(),
        ),
    ]
